- .github/workflows/ci.yaml
- src/stac_asset/client.py
- src/stac_asset/earthdata_client.py
- src/stac_asset/errors.py
- src/stac_asset/filesystem_client.py
- src/stac_asset/functions.py
- src/stac_asset/http_client.py
- src/stac_asset/planetary_computer_client.py
- src/stac_asset/s3_client.py
- src/stac_asset/types.py
- src/stac_asset/usgs_eros_client.py
- Closes #11
Also includes OS in the matrix. Doesn't need a changelog.
> Add matrix

- .github/workflows/ci.yaml
- pyproject.toml
> Add coverage to ci

- CHANGELOG.md
- pyproject.toml
> Release v0.0.4

- README.md
- docs/design-goals.rst
- docs/index.rst
> Move design goals to docs

- MANIFEST.in
> Add py.typed marker

- .pre-commit-config.yaml
- pyproject.toml
Typing seems jank after click v8.1.4
> Fix click typing

- src/stac_asset/errors.py
- src/stac_asset/functions.py
> Add asset key to download error

- CHANGELOG.md
- src/stac_asset/__init__.py
- src/stac_asset/_cli.py
- src/stac_asset/_download.py
- src/stac_asset/client.py
- src/stac_asset/config.py
- src/stac_asset/strategy.py
- tests/test_functions.py
Allow finer-grained control of what happens to assets if they error on download.
> Add DownloadStrategy

- src/stac_asset/_cli.py
- src/stac_asset/_download.py
- src/stac_asset/config.py
- src/stac_asset/functions.py
- tests/test_functions.py
- tests/test_s3_client.py
> Remove `file_name` from `Config`

- CHANGELOG.md
- src/stac_asset/_functions.py
- tests/test_functions.py
If a user asks to include (or exclude) assets, we should remove the un-included assets from the item.
> Remove non-included assets

- src/stac_asset/_cli.py
- src/stac_asset/_functions.py
- tests/test_functions.py
> Fix fail fast

- src/stac_asset/_cli.py
- src/stac_asset/_functions.py
> One progress bar

- src/stac_asset/_cli.py
- src/stac_asset/_functions.py
- src/stac_asset/messages.py
> Add better error reporting to cli

- README.md
- docs/api.rst
- docs/cli.rst
- docs/conf.py
- docs/index.rst
- pyproject.toml
- src/stac_asset/__init__.py
- src/stac_asset/_cli.py
- src/stac_asset/_functions.py
- src/stac_asset/client.py
- src/stac_asset/earthdata_client.py
- src/stac_asset/http_client.py
- src/stac_asset/s3_client.py
- src/stac_asset/validate.py
- tests/test_functions.py
Turns out that writing docs help make our APIs better, who knew?
> Add pre-configured clients, docs fixups

- docs/environment.yaml
> Build w/ CLI on readthedocs

- src/stac_asset/_cli.py
- src/stac_asset/_functions.py
- src/stac_asset/messages.py
- tests/conftest.py
- tests/test_cli.py
> More cli fixups

- CHANGELOG.md
- src/stac_asset/__init__.py
- src/stac_asset/_functions.py
- src/stac_asset/client.py
- src/stac_asset/http_client.py
- src/stac_asset/planetary_computer_client.py
- src/stac_asset/s3_client.py
- tests/test_filesystem_client.py
- tests/test_functions.py
- tests/test_http_client.py
- tests/test_planetary_computer_client.py
- tests/test_s3_client.py
> Add asset_exists and href_exists

- README.md
- Closes #88 (any issues closed by this pull request)
Short description of the pull request.
> Update README.md typo on example

- CHANGELOG.md
- src/stac_asset/_functions.py
- tests/test_functions.py
- Didn't quite do it right in #96, needed the handle the case when the download directory is not absolute
> Actually make absolute hrefs

- README.md
- Closes https://github.com/stac-utils/stac-asset/issues/98
Demonstrate usage of *await* keyword
> fix, docs: add await usage to readme.md

- CHANGELOG.md
- src/stac_asset/__init__.py
- src/stac_asset/_functions.py
- src/stac_asset/blocking.py
- tests/test_blocking.py
- tests/test_functions.py
> Add read_href method

- .readthedocs.yaml
- docs/environment.yaml
> Don't use mambaforge for readthedocs

- CHANGELOG.md
- src/stac_asset/_functions.py
- src/stac_asset/blocking.py
- tests/test_functions.py
Allows us to keep the assets we don't download.
> Add keep_non_downloaded

- .github/workflows/ci.yaml
- pyproject.toml
> Test and advertise python 3.12

- .pre-commit-config.yaml
- CHANGELOG.md
- pyproject.toml
> release prep 0.3.0

- CHANGELOG.md
- src/stac_asset/config.py
- src/stac_asset/http_client.py
- tests/test_http_client.py
- Closes #161
Short description of the pull request.
> feat: add HttpClient timeout config

- CHANGELOG.md
- pyproject.toml
- src/stac_asset/_cli.py
- src/stac_asset/config.py
- src/stac_asset/http_client.py
- tests/test_http_client.py
- Closes https://github.com/stac-utils/stac-asset/issues/191
Adds the ability to configure http retry behavior.
> feat: add http retry config

- CHANGELOG.md
- src/stac_asset/messages.py
> Fix SkipAssetDownload docstring

- CHANGELOG.md
- src/stac_asset/_cli.py
- Closes #197
Copy the fix in #160 to the CLI reporting. @drnextgis can you check to see if this fixes the issue for you? 🙇🏼
> Add more info to CLI error message
