stac-utils/stac-asset

- CHANGELOG.md
- src/stac_asset/client.py
- tests/conftest.py
- tests/test_filesystem_client.py
- Closes #6 
Also includes a change to the `item_file_name` behavior -- now, we default to `item.json`, and if it's `None` don't write the file.
> Download item collections

- CHANGELOG.md
- docs/conf.py
- src/stac_asset/__init__.py
- src/stac_asset/_cli.py
- src/stac_asset/client.py
- src/stac_asset/config.py
- src/stac_asset/errors.py
- src/stac_asset/functions.py
- tests/test_cli.py
- tests/test_config.py
- tests/test_filesystem_client.py
- tests/test_s3_client.py
We were passing around a _lot_ of arguments. This PR refactors to use a configuration object. Breaking change.
We will need to figure out a strategy for specific clients to advertise their configuration -- for now, we have an ad-hoc "use an environment variable" policy for some of them.
> Refactor to use a config object

- CHANGELOG.md
- src/stac_asset/__init__.py
- src/stac_asset/_cli.py
- src/stac_asset/client.py
- src/stac_asset/config.py
- src/stac_asset/earthdata_client.py
- src/stac_asset/errors.py
- src/stac_asset/filesystem_client.py
- src/stac_asset/functions.py
- src/stac_asset/http_client.py
- src/stac_asset/planetary_computer_client.py
- src/stac_asset/s3_client.py
- tests/data/LC09_L2SP_092068_20230607_20230609_02_T1_SR.json
- tests/test_cli.py
- tests/test_earthdata_client.py
- tests/test_filesystem_client.py
- tests/test_functions.py
- tests/test_planetary_computer_client.py
- tests/test_s3_client.py
- Partial #39 (needs `abfs` support to be a full fix)
- Closes #2
Refactor lots of stuff to support multiple clients. Clients no longer have `download_item` and `download_item_collection`, as the client-picking logic lives above the client itself.
Adds some extra stuff, including a content type check to help error on 200 responses with login pages (hi USGS).
> Support multiple clients per item

- src/stac_asset/_cli.py
- src/stac_asset/functions.py
- tests/test_functions.py
- Closes #52
We were being too liberal setting an item's self href, which was leading to invalid item collection asset hrefs.
> Fix item collection asset hrefs

- .github/workflows/ci.yaml
- .pre-commit-config.yaml
- CHANGELOG.md
- pyproject.toml
- src/stac_asset/_cli.py
- src/stac_asset/client.py
- src/stac_asset/config.py
- src/stac_asset/filesystem_client.py
- src/stac_asset/functions.py
- src/stac_asset/http_client.py
- src/stac_asset/messages.py
- src/stac_asset/planetary_computer_client.py
- src/stac_asset/s3_client.py
- tests/test_cli.py
- tests/test_functions.py
- Closes #4
It's not that shiny, but it's a start, and the queue plumbing is the more important part.
> Progress reporting

- CHANGELOG.md
- src/stac_asset/__init__.py
- src/stac_asset/_cli.py
- src/stac_asset/_download.py
- src/stac_asset/client.py
- src/stac_asset/errors.py
- src/stac_asset/functions.py
- tests/test_functions.py
Now we use the same basic infrastructure for item collections and items. The same client will be used for multiple items.
Breaking because it removes the `guess*` function.
> Abstract downloading

- CHANGELOG.md
- src/stac_asset/_download.py
- src/stac_asset/validate.py
- tests/test_validate.py
- Closes #60 
Always allow `octet-stream` results.
> Allow binary/octet-stream always

- CHANGELOG.md
- src/stac_asset/_cli.py
- src/stac_asset/_download.py
- src/stac_asset/config.py
> Add overwrite option

- CHANGELOG.md
- src/stac_asset/__init__.py
- src/stac_asset/_cli.py
- src/stac_asset/_functions.py
- src/stac_asset/client.py
- src/stac_asset/config.py
- src/stac_asset/errors.py
- src/stac_asset/filesystem_client.py
- src/stac_asset/http_client.py
- src/stac_asset/messages.py
- src/stac_asset/planetary_computer_client.py
- src/stac_asset/s3_client.py
- src/stac_asset/strategy.py
- tests/test_config.py
- tests/test_functions.py
- Adds a `fail_fast` option to the config
- Splits out `warn` from `error_strategy`
- Adds a `Message` superclass
> Add fast fails, split warn and error strategy

- CHANGELOG.md
- src/stac_asset/__init__.py
- src/stac_asset/_functions.py
- src/stac_asset/client.py
- src/stac_asset/filesystem_client.py
- src/stac_asset/http_client.py
- src/stac_asset/planetary_computer_client.py
- src/stac_asset/s3_client.py
- tests/test_functions.py
- Closes #84 
Gives us more insight into why the existence check failed.
> Add assert_asset_exists, assert_href_exists

- CHANGELOG.md
- README.md
- docs/api.rst
- pyproject.toml
- src/stac_asset/__init__.py
- src/stac_asset/_cli.py
- src/stac_asset/_functions.py
- src/stac_asset/blocking.py
- src/stac_asset/types.py
- tests/test_blocking.py
- tests/test_functions.py
- Closes #82
It'll be a slight pain to keep the blocking interface up-to-date with the non-blocking, but that's what we have to do I guess.
> Add blocking interface

- .pre-commit-config.yaml
- CHANGELOG.md
- pyproject.toml
- src/stac_asset/_cli.py
- tests/test_cli.py
- Closes #80 
@matthewhanson is this more-or-less what you're looking for from an existence check?
```shell
$ stac-client search \
https://earth-search.aws.element84.com/v1 \
-c sentinel-2-l2a \
--max-items 1 | \
stac-asset info --s3-requester-pays
Asset              Client    Exists    Media type                                                Note
-----------------  --------  --------  --------------------------------------------------------  ------------------------------------------------------------------------
aot                http      True      image/tiff; application=geotiff; profile=cloud-optimized
aot-jp2            s3        False     image/jp2                                                 An error occurred (404) when calling the HeadObject operation: Not Found
blue …
```
> Add info command

- CHANGELOG.md
- src/stac_asset/_functions.py
- tests/test_functions.py
PySTAC doesn't set self href when reading from file, so it's awkward to use relative paths. Plus, most folks expect item collections to have absolute b/c they're from searches or whatever.
> Use absolute paths for item collections

- README.md
- Closes #109 
This PR adds a note about how to make `stac_asset.blocking` functions work inside a notebook.
Example usages of the workaround:
- https://colab.research.google.com/drive/1Gofatz0sUIhbBj64K15Dkj-4raejKBF2#scrollTo=grf6rsueMSi4
- https://github.com/stac-utils/stac-task/pull/42/files#diff-0ed2cf4aaeba2d2a23f6230accc39f7aedcf80e0feea2a89639c7633282f293aR148-R156
> Document how to allow blocking requests when asyncio is running

- CHANGELOG.md
- src/stac_asset/__init__.py
- src/stac_asset/_functions.py
- tests/test_functions.py
- n/a
I have a case where I am using `read_href`, but can significantly decrease memory usage if I use the chunks as they are downloaded rather than waiting for the the complete byte stream from `read_href`. Seeing that `read_href` is concatenating a stream, this change simply splits the chunked downloading from `read_href` into a new method `stream_href`, which `read_href` uses internally.
> feat: add stream_href method

- .github/workflows/release.yaml
I set up trusted publishers in PyPI and test PyPI, so this _should_ work?
> Remove tokens from release workflow

- .github/workflows/ci.yaml
`macos-latest` is arm64, and doesn't have older Pythons.
> Exclude bad matrix configs

- CHANGELOG.md
- src/stac_asset/_functions.py
- tests/test_functions.py
- n/a
While testing stac-task, I observed that the test that requested a non-existent asset name to be downloaded (or, I believe, and case where no assets are downloaded) resulted in an error writing the item.json if the working directory didn't already exist. This PR makes sure that directory does exist before writing the json.
> create directory for writing item json

- .github/workflows/ci.yaml
- CHANGELOG.md
- pyproject.toml
- src/stac_asset/_functions.py
- src/stac_asset/client.py
- src/stac_asset/filesystem_client.py
- src/stac_asset/http_client.py
- src/stac_asset/s3_client.py
- src/stac_asset/types.py
- tests/test_functions.py
- n/a
- Deprecate Python 3.8 support.
- Update some typing wrt not needing to support 3.8
> deprecate python 3.8

- CHANGELOG.md
- README.md
- pyproject.toml
- tests/cassettes/test_http_client/test_href_exists.yaml
- tests/cassettes/test_planetary_computer_client/test_href_exists.yaml
- tests/cassettes/test_s3_client/test_href_exists.yaml
- tests/test_cli.py
- tests/test_http_client.py
- tests/test_planetary_computer_client.py
- Closes #164 
I can't completely do away with `--network-access` because the download-file-size-checks don't work with **pytest-vcr**. cc @drnextgis
> Add a few vcr marks

- CHANGELOG.md
- src/stac_asset/_functions.py
The Downloads class manages concurrent downloads using asynchronous tasks. However, due to operating system's limits, an _[Errno 24] Too many open files_ may occur, when many files are downloaded in parallel. Rather than launching an asynchronous task for every single download all at once, this PR introduces a semaphore to limit the number of downloads that can run in parallel. This prevents hitting the file descriptor limit.
> fix: limit number of concurrently opened files

- src/stac_asset/http_client.py
- src/stac_asset/planetary_computer_client.py
- src/stac_asset/s3_client.py
- Closes #165 
I didn't understand **sphinx-autodoc** well enough...seems better to document inside the `__init__` method on assignment. cc @drnextgis. No tests or CHANGELOG needed.
> Move attributes docs to __init__

- CHANGELOG.md
- src/stac_asset/__init__.py
- src/stac_asset/_functions.py
- src/stac_asset/blocking.py
- tests/test_blocking.py
- tests/test_functions.py
> Add download_file

- CHANGELOG.md
- src/stac_asset/validate.py
- tests/test_validate.py
Allow content types text/xml and application/xml to be used interchangeably
N/A
The XML content types `text/xml` and `application/xml` are sometimes used interchangeably in different places. For example, the STAC metadata may reference one, but the web server for downloading may report the other one. Right now, such a scenario would cause an error when content type validation is enabled.
https://datatracker.ietf.org/doc/html/rfc2376#section-3
> Allow content types text/xml and application/xml to be used interchangeably

- CHANGELOG.md
- src/stac_asset/config.py
- src/stac_asset/earthdata_client.py
- src/stac_asset/http_client.py
- src/stac_asset/planetary_computer_client.py
- tests/test_earthdata_client.py
- Closes #176
After playing around with some dynamic config, I didn't like how complex it made things. Instead, I'll just make sure to bubble up all client attributes to the top-level config.
This is a breaking change that requires a MAJOR version release.
Also:
- Removes `EarthdataClient.login`
- Makes `check_content_type` a non-optional param for `HttpClient.__init__`
> Expose all client attributes in config

- CHANGELOG.md
- src/stac_asset/_functions.py
- tests/test_functions.py
- Closes #102
`derived_from` seemed better than `canonical`, since there might already be a `canonical` link and it doesn't make sense to have two.
> Add derived_from link

- CHANGELOG.md
- src/stac_asset/config.py
- src/stac_asset/s3_client.py
- tests/test_s3_client.py
N/A
This pull request adds support for configuring a custom endpoint URL for the S3Client. This enhancement allows users to specify their own S3 endpoint.
- Verified that S3Client connects to the specified custom endpoint URL.
- Ensured backward compatibility by confirming the default behavior when no custom URL is provided.
Note that this feature only works if you import the functions and use it in your own code; the CLI has not been updated at this time.
> Custom s3 endpoint

- CHANGELOG.md
- README.md
- src/stac_asset/_cli.py
- src/stac_asset/_functions.py
- src/stac_asset/blocking.py
- tests/data/item.json
- tests/test_functions.py
- Closes #58 
Add support for templated paths to specify the location for downloaded files, as outlined in https://pystac.readthedocs.io/en/latest/api/layout.html#pystac.layout.LayoutTemplate.
> feat: add option for templated paths

- CHANGELOG.md
- src/stac_asset/http_client.py
```python
>>> from aiohttp import ClientResponseError, ClientError, ServerDisconnectedError
>>> issubclass(ClientResponseError, ClientError)
True
>>> issubclass(ServerDisconnectedError, ClientError)
True
>>> issubclass(ServerDisconnectedError, ClientResponseError)
False
```
> fix: expand the list of exceptions on which we should retry

- pyproject.toml
- Ignore can be dropped when https://github.com/VITObelgium/aiohttp-oauth2-client/issues/1 is fixed
Includes ignore on aiohttp-oauth2-client deprecation warning.
> Error on pytest warnings

- CHANGELOG.md
- src/stac_asset/_cli.py
- src/stac_asset/_functions.py
- src/stac_asset/blocking.py
- Closes #201 
Better semaphore usage to enforce `max_concurrent_downloads`. Also bubble up `max_concurrent_downloads` all the way to the CLI. cc @drnextgis
> Improve max concurrent downloads

- CHANGELOG.md
- src/stac_asset/_cli.py
- Closes #205 
We were incorrectly assuming that asset keys were unique in the CLI reporting 🤦🏼. cc @drnextgis
> Fix id+key reporting in cli

- CHANGELOG.md
- src/stac_asset/_cli.py
- src/stac_asset/_functions.py
- src/stac_asset/client.py
- src/stac_asset/filesystem_client.py
- src/stac_asset/http_client.py
- src/stac_asset/planetary_computer_client.py
- src/stac_asset/s3_client.py
Fixes https://github.com/stac-utils/stac-asset/issues/202
> Add non-streaming download option

- CHANGELOG.md
- src/stac_asset/_cli.py
- src/stac_asset/_functions.py
- src/stac_asset/client.py
- src/stac_asset/filesystem_client.py
- src/stac_asset/http_client.py
- src/stac_asset/planetary_computer_client.py
- src/stac_asset/s3_client.py
This lets clients decide whether to default to streaming or not, e.g. the filesystem client shouldn't stream by default.
- Closes #222
> Allow stream to be None

- CHANGELOG.md
- src/stac_asset/client.py
- tests/test_earthdata_client.py
- Related to #234 in that there wasn't a path to using the earthdata client.
Sets the default client to be EarthdataClient when "earthdata" is in a https url's hostname.
> a guess of the earthdataclient case

- CHANGELOG.md
- src/stac_asset/_cli.py
- Closes #237
Add `--http-header`, which can be specified multiple times, to CLI.
@scottyhq your example would then look like:
```shell
stac-client search https://api.canopy.umbra.space/v2/stac/ \
--headers "authorization=Bearer $UMBRA_API_TOKEN" \
--query "umbra:task_id=644cc5e9-8702-44d8-a154-235d3c8233f2" \
| stac-asset download \
--http-header "authorization=Bearer $UMBRA_API_TOKEN" \
-i "2024-10-28-19-13-59_UMBRA-08_MM.tif"
```
Can you check this branch and see if that works for you? 🙇🏼
> Allow http headers on cli

- CHANGELOG.md
- src/stac_asset/__init__.py
- src/stac_asset/_cli.py
- src/stac_asset/client.py
- src/stac_asset/config.py
- src/stac_asset/earthdata_client.py
- src/stac_asset/filesystem_client.py
- src/stac_asset/http_client.py
- src/stac_asset/planetary_computer_client.py
- src/stac_asset/s3_client.py
- Closes #93 
- Closes #234 
- Follow on issue: https://github.com/stac-utils/stac-asset/issues/240
Bit a YOLO implementation, but I tested locally by forcing s3:
```shell
$ stac-asset download --client s3 tests/data/item.json 2>&1 | grep s3_client -A 1
File "/Users/gadomski/Code/stac-utils/stac-asset/src/stac_asset/s3_client.py", line 113, in open_url
response = await client.get_object(**self._params(url))
```
> Add names to clients

- CHANGELOG.md
- pyproject.toml
- src/stac_asset/http_client.py
- tests/test_http_client.py
- Fixes issue described in https://github.com/VITObelgium/aiohttp-oauth2-client/issues/1
Instead of subclassing the aiohttp ClientSession to support authentication mechanisms, aiohttp now offers support for client middleware since v3.12.0. This PR fixes the warning you got when instantiating a subclass of the ClientSession and now supports OAuth2 via this middleware mechanism.
> feat: support OAuth2 via HTTP client middleware instead of subclass

- CHANGELOG.md
- src/stac_asset/filesystem_client.py
- tests/test_filesystem_client.py
N/A
Add support for local files using file URIs: the href is starting with `file://`.
> Add support for local files using file URIs
